language: php
php:
  - 7.2

before_script:
  - composer install
  - pecl install ds
  - echo "extension=ds.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
script:
  - composer test
  - composer coverage_clover
  - composer require --dev php-coveralls/php-coveralls

after_script:
  - travis_retry php vendor/bin/php-coveralls -v